"""add_paired_devices

Revision ID: 286b527d1174
Revises: de10f91abd65
Create Date: 2026-04-29 23:09:17.206165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286b527d1174'
down_revision: Union[str, None] = 'de10f91abd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paired_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_name', sa.String(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paired_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paired_devices_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paired_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paired_devices_id'))

    op.drop_table('paired_devices')
    # ### end Alembic commands ###
