"""Add goal_id to transactions

Revision ID: 64401e702108
Revises: f7c8d9e0a1b2
Create Date: 2026-05-06 13:40:08.355155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64401e702108'
down_revision: Union[str, None] = 'f7c8d9e0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_goal_id'), ['goal_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_goal_id_goals', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_goal_id_goals', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_goal_id'))
        batch_op.drop_column('goal_id')
    # ### end Alembic commands ###
