"""initial_migration

Revision ID: a139c5630622
Revises: 
Create Date: 2026-04-29 18:55:29.543883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a139c5630622'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration is stamped as applied because:
    # 1. Database already exists with tables created by Base.metadata.create_all()
    # 2. SQLite has limited ALTER support (no ALTER CONSTRAINT, no ALTER COLUMN TYPE)
    # 3. The existing tables are functional for the application
    # 4. Future migrations can add indexes/constraints incrementally if needed
    
    pass  # No-op migration - database is already in the correct state


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # No-op migration - database is already in the correct state
    
    pass
