"""add_authorized_devices_table

Revision ID: a1b2c3d4e5f6
Revises: 286b527d1174
Create Date: 2026-04-30 21:34:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '286b527d1174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorized_devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    with op.batch_alter_table('authorized_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorized_devices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorized_devices_api_key_hash'), ['api_key_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorized_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorized_devices_api_key_hash'))
        batch_op.drop_index(batch_op.f('ix_authorized_devices_id'))

    op.drop_table('authorized_devices')
    # ### end Alembic commands ###
